yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from . import views

app_name = 'posts'


urlpatterns = [
    path('', cache_page(20)(views.index), name='index'),
    path('group/<slug:slug>/', views.groups, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<post_id>/edit/', views.post_edit, name='post_edit'),
    path('create/', views.post_create, name='post_create'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment, name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

urlpatterns = [
    path('auth/', include('users.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),) 
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/templates/includes/comments.html
<!-- Форма добавления комментария -->
{% load user_filters %}

{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{%if post.comments.all %}
{% for comment in post.comments.all %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
      <p>
        {{ comment.text }}
      </p>
    </div>
  </div>
{% endfor %}
{% endif %}

yatube/templates/includes/footer.html
{% load static %}
    <!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
    <footer class="border-top text-center py-3">
        <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>    
    </footer>

yatube/templates/includes/header.html
{% load static %}

<head>    
  <meta charset="utf-8"> <!-- Кодировка сайта -->
  <!-- Сайт готов работать с мобильными устройствами -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
     <!-- Загружаем фав-иконки -->
  <link rel="icon" href="% static img/fav/fav.ico" type="image">
  <!--<link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">-->
  <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
  <meta name="msapplication-TileColor" content="#000">
  <meta name="theme-color" content="#ffffff">
  <!-- Подключен файл со стандартными стилями бустрап -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  
</head>

<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
      {# Добавлено в спринте #}

      {% comment %}
      Меню - список пунктов со стандартными классами Bootsrap.
      Класс nav-pills нужен для выделения активных пунктов 
      {% endcomment %}
      <ul class="nav nav-pills">
        <li class="nav-item">
          <a class="nav-link 
             {% if request.resolver_match.view_name  == 'about:author' %}
                active
             {% endif %}"
          href="{% url 'about:author' %}"
          >
          Об авторе
        </a>
        </li>
        <li class="nav-item">
          <a class="nav-link
             {% if request.resolver_match.view_name  == 'about:tech' %}
                active
             {% endif %}"
          href="{% url 'about:tech' %}">Технологии</a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item"> 
          <a class="nav-link 
             {% if request.resolver_match.view_name  == '' %}
                active
             {% endif %}"
             href="{% url 'posts:post_create' %}">Новая запись</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light
          {% if request.resolver_match.view_name  == 'users:password_reset_form' %}
             active
          {% endif %}"
          href="{% url 'users:password_reset_form' %}">Изменить пароль</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light 
          {% if request.resolver_match.view_name  == 'users:logout' %}
             active
          {% endif %}"
           href="{% url 'users:logout' %}">Выйти</a>
        </li>
        <li>
          <!-- Пользователь: {{ user.username }} -->
          <li class="nav-item"> 
            <a class="nav-link" href="{% url 'posts:profile' user.username %}"> Пользователь: {{ user.username }} </a>
          </li>
        </li>
        {% else %}
        <li class="nav-item"> 
          <a class="nav-link link-light 
          {% if request.resolver_match.view_name  == 'users:login' %}
             active
          {% endif %}"
           href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light 
          {% if request.resolver_match.view_name  == 'users:signup' %}
             active
          {% endif %}"
          href="{% url 'users:signup' %}">Регистрация</a>
        </li>
        {% endif %}
      </ul>
      {# Конец добавленого в спринте #}
    </div>
  </nav>      
</header> 

yatube/templates/includes/postcard.html
{% load thumbnail %}
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
          <p> <a href="{% url 'posts:profile' post.author.username %}">Профиль</a></p>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
    <p>{{ post.text }}</p>

     