yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from . import views

app_name = 'posts'


urlpatterns = [
    path('', cache_page(20)(views.index), name='index'),
    path('group/<slug:slug>/', views.groups, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<post_id>/edit/', views.post_edit, name='post_edit'),
    path('create/', views.post_create, name='post_create'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment, name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

urlpatterns = [
    path('auth/', include('users.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),) 
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    """
    Модели группы.
    """
    title = models.CharField('Название группы',
                             help_text='Заполните данные группы',
                             max_length=200)
    slug = models.SlugField('Короткая ссылка',
                            help_text='Придумайте короткую ссылку',
                            max_length=50, unique=True)
    description = models.TextField('Описание группы',
                                   help_text='Заполните описание группы')

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title


class Post(models.Model):
    """
    Модели публикации.
    """
    text = models.TextField('Текст публикации',
                            help_text='Введите текст публикации')
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True)

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
        help_text='Укажите автора публикации'
    )

    group = models.ForeignKey(
        Group,
        blank=True, null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text=('Выберите, относится ли публикация '
                   'к какой-либо группе, или оставьте поле пустым')
    )

    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Публикация'
        verbose_name_plural = 'Публикации'

    def __str__(self):
        return '{text}, {date:%Y-%m-%d}, {author}, {group}'.format(
            text=self.text[:15],
            date=self.pub_date,
            author=self.author.username,
            group=self.group
        )


class Comment(models.Model):
    """
    Модели комментариев.
    """
    text = models.TextField('Комментарий',
                            help_text='Напишите Комментарий',
                            max_length=200)
    created = models.DateTimeField(
        'Дата публикации комментария',
        auto_now_add=True)
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Комментарий',
        help_text='Укажите пост для комментирования'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор',
        help_text='Укажите автора комментария'
    )

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.text


class Follow(models.Model):
    """
    Модели подписки.
    """
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик',
        help_text='Кто хочет подписаться',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор',
        help_text='Автор, на которого хотите подписаться',
    )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'], name='unique_follow'
            )
        ]

    def __str__(self):
        return '{user}, {author}'.format(
            author=self.author.username,
            user=self.user.username
        )

yatube/posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    """
    Форма создания поста
    """
    class Meta:
        model = Post
        fields = ('group', 'text', 'image')


class CommentForm(forms.ModelForm):
    """
    Форма создания  комментария
    """
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from .models import Post, Group, Follow
from .forms import PostForm, CommentForm
from .utils import paginator_calculate


User = get_user_model()

QUANTITY_OF_POSTS_ON_PAGE = 10


def index(request):
    """
    Главная страница.
    """
    template = 'posts/index.html'
    post_list = Post.objects.all()
    page_obj = paginator_calculate(request,
                                   post_list,
                                   QUANTITY_OF_POSTS_ON_PAGE)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def groups(request, slug):
    """
    Посты Группы.
    """
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    page_obj = paginator_calculate(request,
                                   post_list,
                                   QUANTITY_OF_POSTS_ON_PAGE)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    """
    Профиль.
    """
    author = get_object_or_404(User, username=username)
    post_list = author.posts.all()
    post_count = post_list.count()
    page_obj = paginator_calculate(request,
                                   post_list,
                                   QUANTITY_OF_POSTS_ON_PAGE)

    if request.user.is_authenticated:
        following = Follow.objects.filter(
            user=request.user, author=author
        ).exists()
    else:
        following = False
    template = 'posts/profile.html'
    context = {
        'author': author,
        'post_list': post_list,
        'page_obj': page_obj,
        'post_count': post_count,
        'following': following,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    """
    Посты автора.
    """
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post, pk=post_id)
    post_count = post.author.posts.count()
    form = CommentForm(request.POST or None)
    context = {
        'post_count': post_count,
        'post': post,
        'form': form,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    """
    Создание поста.
    """
    if request.method == 'POST':
        form = PostForm(request.POST, files=request.FILES or None)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', request.user.username)
    form = PostForm()
    template = 'posts/create_post.html'
    context = {
        'form': form,
    }
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    """
    Редактирование поста.
    """
    is_edit = True
    post = get_object_or_404(Post, pk=post_id)
    group = post.group
    if post.author == request.user:
        if request.method == 'POST':
            form = PostForm(
                request.POST, files=request.FILES or None, instance=post
            )
            if form.is_valid():
                post = form.save()
                return redirect('posts:post_detail', post_id=post.id)
        else:
            form = PostForm(files=request.FILES or None, instance=post)
            context = {'form': form,
                       'post': post,
                       'group': group,
                       'is_edit': is_edit, }
            return render(request, 'posts/create_post.html', context)
    return redirect('posts:post_detail', post_id=post.id)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user)
    page_obj = paginator_calculate(request,
                                   post_list,
                                   QUANTITY_OF_POSTS_ON_PAGE)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    user = request.user
    author = User.objects.get(username=username)
    is_follower = Follow.objects.filter(user=user, author=author)
    if user != author and not is_follower.exists():
        Follow.objects.create(user=user, author=author)
    return redirect('posts:profile', username=author)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    is_follower = Follow.objects.filter(user=request.user, author=author)
    if is_follower.exists():
        is_follower.delete()
    return redirect('posts:profile', username=author)

yatube/templates/posts/create_post.html
{% extends 'base.html' %} 
{% load static %}
{% load thumbnail %}
{% block title %}  
  {% if is_edit %}
     Редактировать запись
  {% else %}
     Добавить запись
  {% endif %}
{% endblock %}

{% block content %}
{% load user_filters %}
    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                {% if is_edit %}
                  Редактировать запись
                {% else %}
                  Добавить запись
                {% endif %}            
              </div>
              <div class="card-body">        
                <form method="post" enctype="multipart/form-data" {% url 'posts:post_create'%}>
                  {% csrf_token %}
                 
                  {% for field in form %} 
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {# К полю ввода добавляем атрибут class #}
                  {{ field|addclass:'form-control' }} 
                    {% if field.help_text %}
                      <small 
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                    {% else %}
                    Добавить
                    {% endif %} 
                </button>
              </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
{% endblock %}

yatube/templates/posts/follow.html
<!-- templates/posts/follow.html -->
{% extends 'base.html' %} 
{% load static %}
{% load thumbnail %}
{% block title %}  Последние обновления по подпискам{% endblock %}

{% block content %}
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">
        <h1> Последние обновления по подпискам </h1>
        <hr>   
        <article>
          {% for post in page_obj %}
            {% include  'includes/postcard.html'%}
            {% if post.group %}
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            <!-- <a href="">все записи группы</a>-->
            {% endif %}
          {% if not forloop.last %}<hr>{% endif %}
          {% endfor %} 
        </article>
        <!-- под последним постом нет линии -->
        {% include 'posts/includes/paginator.html' %}
      </div>
{% endblock %}

yatube/templates/posts/group_list.html
<!-- templates/posts/group_list.html -->
{% extends 'base.html' %} 
{% load static %}
{% load thumbnail %}
{% block title %} Посты Группы {{ group.title }} {% endblock %}
{% block content %}
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">
        {% block header %}<h1> {{ group.title }} </h1> {% endblock %}
        <p>{{ group.description }}</p>
        <article>
          {% for post in page_obj %}
            {% include  'includes/postcard.html'%}
            {% if not forloop.last %}<hr>{% endif %}
          {% endfor %} 
        </article>
      {% include 'posts/includes/paginator.html' %}
    </div>
{% endblock %}

yatube/templates/posts/index.html
<!-- templates/posts/index.html -->
{% extends 'base.html' %} 
{% load static %}
{% load thumbnail %}
{% block title %}  Последние обновления на сайте{% endblock %}

{% block content %}
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">
        <h1> Последние обновления на сайте </h1>
        <hr>   
        <article>
          {# #}
          {% include 'posts/includes/switcher.html' %} 

          {% for post in page_obj %}
            {% include  'includes/postcard.html'%}
            {% if post.group %}
            <li>
              <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            <!-- <a href="">все записи группы</a>-->
            </li>
            {% endif %}
          <li>
              <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
          </li>
          {% if not forloop.last %}<hr>{% endif %}
          {% endfor %} 
        </article>
        {% include 'posts/includes/paginator.html' %}
      </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %} 
{% load static %}
{% load thumbnail %}
{% block title %} Пост {{ post|slice:":5" }} {# 30 символовне много ли для заголовка?#} {% endblock %}
{% block content %}
  <div class="container py-5">
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y"  }}
            </li>
            <!-- если у поста есть группа -->
            {% if post.group %}          
            <li class="list-group-item">
              Группа:  {{ post.group.title }}
              <a href="{% url 'posts:group_list' post.group.slug %}">
              Все записи группы
              </a>
            {% endif %}
            </li>
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span > {{ post_count }} </span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author %}">
                Все посты пользователя
              </a>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:post_edit' post.id %}">
                Редактировать запись
              </a>
            </li>
          </ul>
          
        </aside>
         
        <article class="col-12 col-md-9">
            <p> </p>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            <p> 
              {{ post.text }}
            </p>
        
          <p> </p>

          {% include 'includes/comments.html' %} 
        </article>
      </div>
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %} 
{% load static %}
{% load thumbnail %}
{% block title %} Профайл пользователя {{ author.get_full_name }} {% endblock %}
{% block content %}
      <div class="container py-5">
        <div class="mb-5">
          <h1>Все посты пользователя: {{ author.get_full_name }} <!--Лев Толстой--> </h1>
          <h3>Всего постов: {{ post_count }} </h3>
          {% if request.user != author %}
          {% if following %}
            <a
              class="btn btn-lg btn-light"
              href="{% url 'posts:profile_unfollow' author.username %}" role="button"
            >
              Отписаться
            </a>
          {% else %}
            <a
              class="btn btn-lg btn-primary"
              href="{% url 'posts:profile_follow' author.username %}" role="button"
            >
              Подписаться
            </a>
          {% endif %}
          {% endif %}
        </div>
        <article>
          <ul>
            <li>
              Автор: {{ author.get_full_name }} <!--Лев Толстой-->
              {# <a href="<!-- фиг знает как сделать; должно вести на первую страницу?-->">все посты пользователя</a> #}
            </li>
          </ul>

        </article>
        <article >
          {% for post in page_obj %}
            <ul>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
            </ul>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            <p>{{ post.text }}</p>

              {% if post.group %}
                <p> <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a></p>
              {% endif %}
            <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
            {% if not forloop.last %}<hr>{% endif %}
          {% endfor %} 
        </article>
        <hr> 
        {% include 'posts/includes/paginator.html' %}
      </div>
{% endblock %}